### ISSUE TITLE
Can't work in IntelliJ IDEA 2021.3.1 (Community Edition)

### ISSUE THREAD

**Issue by eqzip** [lorenzobilli/Eclipse-color-theme#1]
Dear,
  Thank you for you development this theme for Eclipse user! But which can't work in "IntelliJ IDEA 2021.3.1 (Community Edition) Build #IC-213.6461.79, built on December 29, 2021". The install can success but after installed it which can't show in the theme select menu!

With BRs

**Comment by lorenzobilli** [comment]
Hi,
Did you try also the released versions in the Jetbrains plugin store?
Light theme -> https://plugins.jetbrains.com/plugin/18146-eclipse-classic-light-color-scheme
Dark theme -> https://plugins.jetbrains.com/plugin/18145-eclipse-classic-dark-color-scheme

**Comment by eqzip** [comment]
Just like the pictures up. I have already installed this version but which can't show in the theme select combo list.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lorenzobilli/Eclipse-color-theme"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月19日(星期三) 下午5:03
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [lorenzobilli/Eclipse-color-theme] Can't work in IntelliJ IDEA 2021.3.1 (Community Edition) (Issue #1)





 
Hi,
 Did you try also the released versions in the Jetbrains plugin store?
 Light theme -&gt; https://plugins.jetbrains.com/plugin/18146-eclipse-classic-light-color-scheme
 Dark theme -&gt; https://plugins.jetbrains.com/plugin/18145-eclipse-classic-dark-color-scheme
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by lorenzobilli** [comment]
I've just tested it on the Community edition build 2021.3.1 and it's working fine. Are you searching in the correct section? It should appear under "Editor -> Color scheme -> Scheme". It is NOT under "Appearance & behavior -> Appearance -> Theme"!

**Comment by eqzip** [comment]
Thank you very much! Wish you have a nice day!


With BRs
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lorenzobilli/Eclipse-color-theme"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月24日(星期一) 晚上9:24
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [lorenzobilli/Eclipse-color-theme] Can't work in IntelliJ IDEA 2021.3.1 (Community Edition) (Issue #1)





 
I've just tested it on the Community edition build 2021.3.1 and it's working fine. Are you searching in the correct section? It should appear under "Editor -&gt; Color scheme -&gt; Scheme". It is NOT under "Appearance &amp; behavior -&gt; Appearance -&gt; Theme"!
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
