### ISSUE TITLE
Color is not applied to VSCode's side bar

### ISSUE THREAD

**Issue by Wdestroier** [lorenzobilli/Eclipse-color-theme#2]
The theme is working very well, but the theme color is not applied to the side bar. Example:

![image](https://user-images.githubusercontent.com/14764307/215288450-e4753709-f932-4c61-857a-04922b67ea50.png)

I believe this is a theme issue, because other themes can apply a light, green or different color. Example (solarized light theme):

![image](https://user-images.githubusercontent.com/14764307/215288481-c064b89b-75db-4591-b0b9-ed44264d5ee4.png)

Reference: [Support to theme the entire workbench](https://github.com/microsoft/vscode/issues/3112#top)

**Comment by lorenzobilli** [comment]
Yep, I confirm it's a theme issue: right now both the dark and the light theme are only theming the editor. I'm working on a much more improved version that will theme also the workbench, other than improving the syntax coloring for certain languages. Thanks for your patience!

**Comment by Wdestroier** [comment]
Still, this theme is much more consistent than all the others I could find. Definitely underrated extension. Thank you for everything.

**Comment by lorenzobilli** [comment]
Version 0.2.0 is out with preliminary support for workbench theming. Thanks for your feedback!
